name: Deploy PR Previews

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - closed

permissions:
  contents: write

jobs:
  deploy-preview:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout PR Branch
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: npm ci

      - name: Build Frontend
        run: npm run build:production

      - name: Deploy Preview
        if: github.event.action != 'closed'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
          destination_dir: pr-previews/${{ github.event.number }}

      - name: Cleanup Preview for Closed PR
        if: github.event.action == 'closed'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./empty-dir
          destination_dir: pr-previews/${{ github.event.number }}
